### PR TITLE
fix #342 - check loggedIn after receiving login error.

### LINKED ISSUE #342: authentication failed if user session expired before
1. log on 
2. let session expire
3. open http://<yourhost>/login
4. login 
5. NOK: error message: authentication failed

workaround:
just use this URL without "/login": http://<yourhost>

serverlog of API:
```
2017-02-17 14:46:08.070  WARN 1863 --- [http-nio-8080-exec-3] d.m.ui.web.config.RestExceptionLogger    : Got REST exception from handler=public de.metas.ui.web.login.json.JSONLoginAuthResponse de.metas.ui.web.login.LoginRestController.authenticate(java.lang.String,java.lang.String)

de.metas.ui.web.login.exceptions.AlreadyLoggedInException: User already logged in
        at de.metas.ui.web.session.UserSession.assertNotLoggedIn(UserSession.java:205)
        at de.metas.ui.web.session.UserSession$$FastClassBySpringCGLIB$$df3ca08c.invoke(<generat
```

### PR DESCRIPTION
**Pull request by chmieludaniel**

### CODE REVIEW

File: src/components/app/LoginForm.js [hunk 1]
```diff
@@ -59,6 +60,19 @@ class LoginForm extends Component {
 
     }
 
+    checkIfAlreadyLogged(err){
+        const {dispatch} = this.props;
+
+        return dispatch(localLoginRequest())
+            .then(response => {
+                if (response.data){
+                    return location.href = '/';
```
Comment (damianprzygodzki) [inline src/components/app/LoginForm.js]: Why you didn't use react router?

Comment (chmieludaniel) [inline src/components/app/LoginForm.js]: cause, (imo) the page needs reload. When I used router's push, it threw an error related to redux state updates - "Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component...."
wdyt

Comment (damianprzygodzki) [inline src/components/app/LoginForm.js]: First, if you have that error, it means that something is did wrong way. You should probably cancel some promise.
2nd, i see that i should investigate more that case, because im not sure about the solution

Comment (damianprzygodzki) [inline src/components/app/LoginForm.js]: Solution is ok. But we cannot leave the refreshing page like that here.

Comment (damianprzygodzki) [inline src/components/app/LoginForm.js]: @chmieludaniel
