### PR TITLE
fix #155 - No connection info fixed. former ErrorScreen displayed

### LINKED ISSUE #155: Offline mode is not detected
Test:
* webui server is down
* trying to open the frontend in a browser tab
* i get no info about the fact that i am offline

image

### PR DESCRIPTION
**Pull request by chmieludaniel**

### CODE REVIEW

File: src/components/Container.js [hunk 1]
```diff
@@ -48,4 +49,6 @@ class Container extends Component {
     }
 }
 
-export default Container;
+export default connect(state => ({
```
Comment (damianprzygodzki) [inline src/components/Container.js]: Please, @chmieludaniel keep the same format of mapping state to props. Use mapStateToProps function with fallback and propTypes validation.
